### ISSUE TITLE
Unleet won't work at all

### ISSUE THREAD

**Issue by WillTDA** [cityssm/unleet#124]
![image](https://user-images.githubusercontent.com/62032600/104094801-08699100-528b-11eb-9fb7-1e26ef88155a.png)

I get this error whenever I use the package. Is there anything I can do, or is this a bug?

**Comment by dangowans** [comment]
Looking into it now.

**Comment by dangowans** [comment]
Preparing release.

**Comment by dangowans** [comment]
There's a new release up now that will better handle `null` input.

The unleet function accepts string values as input.  For best results, make sure to pass a string value to the function.

Thanks for the issue report!
